package webui

var workflowHintKeys = map[string]string{
	"OwnGit does not pass outputs between jobs. Compute the value in the job that uses it, or merge the two jobs.": "hint.outputs",
	"Use env in the workflow, or a secret.":                                    "hint.vars",
	"OwnGit fills only the event fields listed in its workflow documentation.": "hint.event",
	"Compute the hash in a run step, for example with sha256sum.":              "hint.hashFiles",
}

var workflowEffectTexts = map[string]struct{ en, ko string }{
	"OwnGit does not use this GitHub setting.":   {"OwnGit does not use this GitHub setting", "OwnGit은 이 GitHub 설정을 사용하지 않습니다"},
	"OwnGit gives workflows no GitHub token.":    {"OwnGit gives workflows no GitHub token", "OwnGit은 워크플로에 GitHub 토큰을 주지 않습니다"},
	"OwnGit keeps no cache.":                     {"OwnGit keeps no cache", "OwnGit은 캐시를 보관하지 않습니다"},
	"OwnGit does not pass outputs between jobs.": {"OwnGit does not pass outputs between jobs", "OwnGit은 작업 사이에 출력값을 넘기지 않습니다"},
}

var workflowArgTexts = map[string]map[string]string{
	"workflow.context.hint": {
		"Use a context available at this key.":     "이 키에서 사용할 수 있는 컨텍스트를 쓰세요.",
		"Use a documented context field.":          "문서에 나온 컨텍스트 필드를 쓰세요.",
		"Use step outputs, outcome or conclusion.": "단계의 outputs, outcome 또는 conclusion을 쓰세요.",
		"Use status functions in if.":              "상태 함수는 if에서 쓰세요.",
	},
	"workflow.function.hint": {
		"Replace it with a supported expression function.": "지원하는 표현식 함수로 바꾸세요.",
	},
	"workflow.yaml.detail": {
		"use UTF-8": "UTF-8을 쓰세요",
	},
	"workflow.yaml_feature.feature": {
		"a second document": "두 번째 문서",
		"a merge key (<<)":  "병합 키(<<)",
		"a tag":             "태그",
	},
	"workflow.wrong_type.expected": {
		"a string":                                   "문자열",
		"an event name, list or mapping":             "이벤트 이름, 목록 또는 매핑",
		"at least one event":                         "하나 이상의 이벤트",
		"only branches or branches-ignore, not both": "branches 또는 branches-ignore 중 하나",
		"only paths or paths-ignore, not both":       "paths 또는 paths-ignore 중 하나",
		"only tags or tags-ignore, not both":         "tags 또는 tags-ignore 중 하나",
		"a nonempty list":                            "비어 있지 않은 목록",
		"patterns without ! in an ignore filter":     "제외 필터에서 !를 쓰지 않는 패턴",
		"a list of cron entries":                     "cron 항목 목록",
		"an input identifier":                        "입력 식별자",
		"string, boolean, choice or number (environment is not supported)": "string, boolean, choice 또는 number(environment는 지원하지 않음)",
		"a boolean (use true or false)":                                    "불리언(true 또는 false)",
		"a nonempty list of choices":                                       "비어 있지 않은 선택 항목 목록",
		"a scalar":                                                         "스칼라",
		"a valid input value":                                              "유효한 입력",
		"a runner label or list of labels":                                 "러너 레이블 또는 레이블 목록",
		"a mapping or expression":                                          "매핑 또는 표현식",
		"a nonempty list of steps":                                         "비어 있지 않은 단계 목록",
		"a unique step identifier":                                         "중복되지 않는 단계 식별자",
		"one nonempty run or uses value":                                   "비어 있지 않은 run 또는 uses 중 하나의",
		"inputs only on a uses step":                                       "uses 단계에만 입력",
		"a workflow mapping":                                               "워크플로 매핑",
		"a nonempty mapping of jobs":                                       "비어 있지 않은 작업 매핑",
		"a job identifier up to 100 bytes, starting with a letter or underscore": "영문자 또는 밑줄로 시작하는 100바이트 이하의 작업 식별자",
		"an existing YAML anchor": "존재하는 YAML 앵커",
		"string mapping keys":     "문자열 매핑 키",
		"a mapping":               "매핑",
		"a JSON scalar":           "JSON 스칼라",
		"a list":                  "목록",
		"a value without NUL":     "NUL이 없는",
		"a nonempty group":        "비어 있지 않은 그룹",
		"single or max":           "single 또는 max",
		"queue: max without cancel-in-progress: true":     "cancel-in-progress: true 없이 queue: max",
		"a boolean (use true or false), or an expression": "불리언(true 또는 false) 또는 표현식",
	},
	"workflow.limit.what": {
		"workflow filename":                            "워크플로 파일 이름",
		"workflow files per commit":                    "커밋당 워크플로 파일 수",
		"workflow bytes per commit":                    "커밋당 워크플로 바이트 수",
		"YAML expansion":                               "YAML 확장",
		"Schedules per workflow":                       "워크플로당 일정 수",
		"Steps per job":                                "작업당 단계 수",
		"dispatch inputs":                              "수동 실행 입력 수",
		"expression":                                   "표현식",
		"expression nesting":                           "표현식 중첩 깊이",
		"expression evaluation steps":                  "표현식 계산 단계 수",
		"expression context depth or evaluation steps": "표현식 컨텍스트 깊이 또는 계산 단계 수",
		"JSON value depth":                             "JSON 값 깊이",
		"toJSON output":                                "toJSON 출력",
		"fromJSON input":                               "fromJSON 입력",
		"fromJSON depth":                               "fromJSON 깊이",
		"expression value depth or nodes":              "표현식 값 깊이 또는 노드 수",
		"expression value":                             "표현식 값",
		"matrix expansion steps":                       "매트릭스 확장 단계 수",
		"filter pattern":                               "필터 패턴",
		"concurrency group":                            "동시 실행 그룹",
		"plan per job":                                 "작업당 실행 계획",
		"env variables":                                "env 변수 수",
		"job.env variables":                            "job.env 변수 수",
		"step.env variables":                           "step.env 변수 수",
	},
	"workflow.limit.limit": {
		"100000 nodes or depth 64": "노드 100000개 또는 깊이 64",
		"100 bytes":                "100바이트",
		"200 bytes":                "200바이트",
	},
	"workflow.dispatch_input.reason": {
		"it is not declared":                  "정의되지 않은 입력입니다",
		"it is required":                      "필수 입력입니다",
		"use a UTF-8 scalar without NUL":      "NUL이 없는 UTF-8 스칼라를 쓰세요",
		"the value is longer than 1024 bytes": "값이 1024바이트보다 깁니다",
		"the inputs are larger than 64 KiB":   "입력 전체가 64 KiB보다 큽니다",
		"use true or false":                   "true 또는 false를 쓰세요",
		"use a finite number":                 "유한한 숫자를 쓰세요",
		"choose one of the declared options":  "정의된 선택 항목 중 하나를 고르세요",
		"the input type is not supported":     "지원하지 않는 입력 형식입니다",
	},
	"note.paths_unknown.reason": {
		"the pull request base is unavailable":                          "풀 리퀘스트의 기준 커밋을 사용할 수 없음",
		"the base commit is not usable":                                 "기준 커밋이 유효하지 않음",
		"the base commit is unavailable":                                "기준 커밋을 사용할 수 없음",
		"merge bases could not be read":                                 "병합 기준을 읽을 수 없음",
		"there is not exactly one merge base":                           "병합 기준이 없거나 여러 개임",
		"the tree diff could not be read":                               "트리 차이를 읽을 수 없음",
		"the changed-file list was cut at its file, byte or time limit": "파일 수, 바이트 수 또는 시간 한도로 바뀐 파일 목록이 잘림",
		"the changed-file read reached its time limit":                  "바뀐 파일 읽기가 시간 한도에 도달함",
	},
}
